name: "nix flake update"
on:
  schedule:
    - cron: '15 * * * *'  # 15m
  push:
    branches: [ "master", "repair-self-update" ]

jobs:
  self-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: update
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git fetch --all
        git checkout auto-update

        nix flake update
        nix build .#mkci
        
        mkdir -p .github/workflows
        cp -f result/* .github/workflows
        rm result
        nix flake show --all-systems | sed -r 's/\x1b\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|k]//g' > TMP_README
        echo -e "\`\`\`\n$(cat TMP_README) \n\`\`\`" > README.md || echo "couldnt write file"
        git add .github/workflows README.md || echo "nothing to add!"
        git rm TMP_README result
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "chore: autoupdate"
        title: "chore: autoupdate"
        body: "chore: autoupdate"
        base: master
        branch: chore-autoupdate
        delete-branch: true
