name: "nix flake update"
on:
  schedule:
    - cron: '15 * * * *'  # 15m
  push:
    branches: [ "master", "update-workflow" ]
  pull_request:
    branches: [ "master", "update-workflow" ]

jobs:
  self-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update

    - name: update
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        set -e
        nix build .#mkci
        mkdir -p .github/workflows
        cp -f result/* .github/workflows
        git add .github/workflows
        git stage .github/workflows
        git stage flake.lock
        set +e
        git commit -a -m "chore: update"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
