name: "nix flake update"
on:
  schedule:
    - cron: '15 * * * *'  # 15m
  push:
    branches: [ "master", "repair-self-update" ]

jobs:
  self-update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: update
      id: update
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        nix flake update &> UPDATE_OUTPUT

        if [[ 2 -gt $(wc UPDATE_OUTPUT -l | cut -f 2 -d ' ') ]]; then
          rm UPDATE_OUTPUT
          exit 0
        fi

        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "update<<$EOF" >> $GITHUB_OUTPUT
        echo "update info: " >> $GITHUB_OUTPUT
        cat UPDATE_OUTPUT >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
        
        nix build .#mkci
        mkdir -p .github/workflows
        cp -f result/* .github/workflows
        nix flake show --all-systems | sed -r 's/\x1b\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|k]//g' | sed -e 's/\ *$//g' | (read _x; cat > TMP_README)
        echo -e "\`\`\`.\n$(cat TMP_README) \n\`\`\`" > README.md || echo "couldnt write file"
        git add .github/workflows README.md || echo "nothing to add!"
        rm -f UPDATE_OUTPUT TMP_README result
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "chore: autoupdate"
        title: "chore: autoupdate"
        body: "#Update:\n```${{steps.update.outputs.update}}```"
        base: master
        branch: chore-autoupdate
        delete-branch: true
