name: "nix flake update"
on:
  schedule:
    - cron: '15 * * * *'  # 15m
  push:
    branches: [ "master", "repair-self-update" ]

jobs:
  self-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        nix flake update
        nix build .#mkci || exit 1
    - name: update
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        mkdir -p .github/workflows
        cp -f result/* .github/workflows
        git add .github
        git stage .github flake.lock

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "chore: update"
        title: "chore: update"
        body: "chore: update"
        base: master
        branch: auto-update
        delete-branch: false
